### ISSUE TITLE
UI/UX DESIGN

### ISSUE THREAD

**Issue by alacret** [cobuildlab/okroo-mobile#15]
# PROMOTION DETAILS

Image 1:
![Promotion-Detail-With-Similar-Promotions](https://user-images.githubusercontent.com/918895/55731677-99417780-59e8-11e9-8c40-22bdface8db3.png)

Image 2:
![Promotion-Detail-With-Similar-Promotions-3](https://user-images.githubusercontent.com/918895/55731685-99da0e00-59e8-11e9-8235-19049032a55c.jpg)

- Image size like Image 1
- Keep Address like Image 1
- No logo like Image 1
- Reduce 10% X, SHARE and FAVORITE icons
- Increase 10% Font Size
- Lower a little bit the Picture: 10px
- Put Discount Badge to the Main Promotion. Ex: 80%, also for the news feed
- Try other option of the Shopping Cart, but keep inside the CHECKOUT Button

# SIMILAR PROMOTIONS
Image 3:
![Screen Shot 2019-04-08 at 10 29 57 AM](https://user-images.githubusercontent.com/918895/55732070-4d430280-59e9-11e9-98e5-9326616a42d4.png)

- No picture
- Put `-` and `+` signs to the Similar Promotion

# CHECKOUT Screen

![Screen Shot 2019-04-08 at 10 38 08 AM](https://user-images.githubusercontent.com/918895/55732671-6c8e5f80-59ea-11e9-9879-9cced592ab4f.png)

- `-` and `+` same look and feel that promotions detail
- Treat different the `X` action
- Remove Time
- Change Promotion Title, by Venue Title
- Keep Location
- Indicate Apple Pay or Google Pay

**Comment by alacret** [comment]
![PROMOTION-DETAILS-map](https://user-images.githubusercontent.com/918895/55991484-5ac1ec00-5c78-11e9-98f0-684085d40539.jpg)

- [ ] Move the Address to the end of the screen
- [ ] Increase size on price and promotion
- [ ] Checkout Button all White
- [ ] Add space at the end of the details for DISCLAIMER text

![checkout (1)](https://user-images.githubusercontent.com/918895/55991686-d4f27080-5c78-11e9-8c3f-a0f83132826c.jpg)

- [ ] Remove User Name
- [ ]

**Comment by alacret** [comment]
@ELM4RC0

**Comment by ELM4RC0** [comment]
![checkout-paymet](https://user-images.githubusercontent.com/11633792/56081232-f9655e80-5dd8-11e9-9025-96e11dd2211b.jpg)

**Comment by alacret** [comment]
- [ ] HOME Page: Include area in promotion 
- [ ] Please remove the timestamp (3 hrs ago) from the text.
- [ ] Login. Large social buttons
![Screen Shot 2019-04-22 at 11 29 08 AM](https://user-images.githubusercontent.com/918895/56508312-e3028580-64f1-11e9-8b50-268d999e1561.png)
