### ISSUE TITLE
Detalle de promociones adquiridas 

### ISSUE THREAD

**Issue by mayecham** [cobuildlab/okroo-mobile#6]
como usuario deseo poder ver en mi perfil la lista de promociones que tengo tantos las pendientes por canjear como un historial de las que ya he canejeado. 

ordenes pendientes por redeem 
![Captura de pantalla 2019-08-13 a la(s) 4 23 33 p  m](https://user-images.githubusercontent.com/28816166/62974687-c6fb5a80-bde6-11e9-95cd-d749a3e42086.png)

ordenes ya usadas 
![Captura de pantalla 2019-08-13 a la(s) 4 24 42 p  m](https://user-images.githubusercontent.com/28816166/62974756-e72b1980-bde6-11e9-8c49-2464783990c1.png)

**Comment by ELM4RC0** [comment]
![my-promotion-history](https://user-images.githubusercontent.com/11633792/57151698-934c7580-6d9f-11e9-8ad2-565f53bc5a63.png)
![my-promotion-redeem](https://user-images.githubusercontent.com/11633792/57151699-934c7580-6d9f-11e9-9662-fc6d81d3a402.png)
![my-promotion-redeem-code](https://user-images.githubusercontent.com/11633792/57151700-934c7580-6d9f-11e9-8353-9269b602cf1d.png)
![my-promotion-redeemed](https://user-images.githubusercontent.com/11633792/57151701-93e50c00-6d9f-11e9-83fe-94a41749fcfd.png)

**Comment by rich-97** [comment]
@mayecham ya termine la interfaz, ahora lo voy a integrar con firebase.

**Comment by mayecham** [comment]
@rich-97 recuerda al terminar el issues completo ponerlo con label ready for Qa.

**Comment by rich-97** [comment]
@mayecham ok

**Comment by mayecham** [comment]
listo
